import "./globals.css";
import type { Metadata } from "next";
import { ChakraProvider } from "./providers/chakra-provider";
import { Inter, Fredoka } from "next/font/google";

const fredokaOne = Fredoka({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lucky Victory | Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
